{% set name = "slearn" %}
{% set version = "0.2.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}


source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0ab3a1cc3651a1dbc942c6e88ca7e3093bbf70e762ed7c60b43925678f3a2add


build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - numpy


  run:
    - python >={{ python_min }}
    - scikit-learn
    - pandas
    - numpy
    - scipy
    - lightgbm


test:
  requires:
    - python {{ python_min }}
  imports:
    - slearn


about:
  home: https://github.com/nla-group/slearn
  summary: 'A package linking symbolic representation with scikit-learn machine learning for time series prediction.'
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/nla-group/slearn

extra:
  recipe-maintainers:
    - robcah
    - chenxinye
    - guettel
