{% set name = "slearn" %}
{% set version = "0.2.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}


source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8c966cb63da0a6eaa2d7ba6d3a2dc85cbc0d6b71dd808896fd27993acbdfffea


build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python >=3.6
    - pip
    - numpy


  run:
    - python >=3.6
    - scikit-learn
    - pandas
    - numpy
    - scipy
    - lightgbm


test:
  imports:
    - slearn


about:
  home: https://github.com/nla-group/slearn
  summary: 'A package linking symbolic representation with scikit-learn machine learning for time series prediction.'
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/nla-group/slearn

extra:
  recipe-maintainers:
    - robcah
    - chenxinye
    - guettel
