{% set name = "slearn" %}
{% set version = "0.2.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}


source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 89949289e4e3f2d9ae7862c2eae507b01551fae0f7043c97656f8b0ed736e79e


build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - numpy


  run:
    - python >={{ python_min }}
    - scikit-learn
    - pandas
    - numpy
    - scipy
    - lightgbm
    
    
test:
  requires:
    - python {{ python_min }}
  imports:
    - slearn


about:
  home: https://github.com/nla-group/slearn
  summary: 'A package linking symbolic representation with scikit-learn machine learning for time series prediction.'
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/nla-group/slearn

extra:
  recipe-maintainers:
    - robcah
    - chenxinye
    - guettel
